// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCek-7MoaVSNhVWwUYg8-0KWAWwa4lxLB8',
    appId: '1:211189267610:web:8c969eb24f9eb08504f323',
    messagingSenderId: '211189267610',
    projectId: 'trial-bfc04',
    authDomain: 'trial-bfc04.firebaseapp.com',
    databaseURL: 'https://trial-bfc04-default-rtdb.firebaseio.com',
    storageBucket: 'trial-bfc04.appspot.com',
    measurementId: 'G-9SZZ4J0MEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtWxQ5ud1iO4HqU_OK12q9XkZ9ycQ7jrc',
    appId: '1:211189267610:android:f182c1809664ee1204f323',
    messagingSenderId: '211189267610',
    projectId: 'trial-bfc04',
    databaseURL: 'https://trial-bfc04-default-rtdb.firebaseio.com',
    storageBucket: 'trial-bfc04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMKUNu_fnW95Nt0SlkAmt7cNVh6uMONA8',
    appId: '1:211189267610:ios:c26fd8ff1eda5a9704f323',
    messagingSenderId: '211189267610',
    projectId: 'trial-bfc04',
    databaseURL: 'https://trial-bfc04-default-rtdb.firebaseio.com',
    storageBucket: 'trial-bfc04.appspot.com',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMKUNu_fnW95Nt0SlkAmt7cNVh6uMONA8',
    appId: '1:211189267610:ios:128596763815f97304f323',
    messagingSenderId: '211189267610',
    projectId: 'trial-bfc04',
    databaseURL: 'https://trial-bfc04-default-rtdb.firebaseio.com',
    storageBucket: 'trial-bfc04.appspot.com',
    iosBundleId: 'com.example.trial.RunnerTests',
  );
}
