// food_options.dart

// Define food options for each restaurant
const Map<String, List<String>> foodOptions = {
  'Café Bella': [
    'Pasta Carbonara',
    'Margherita Pizza',
    'Tiramisu',
    'Bruschetta',
    'Caprese Salad',
    'Chicken Alfredo',
    'Mushroom Risotto',
    'Chocolate Lava Cake',
    'Garlic Bread',
    'Tortellini Soup',
    'Cannoli',
    'Spinach Ravioli',
    'Panna Cotta',
    'Fettuccine Alfredo',
    'Italian Wedding Soup',
  ],
  'Rustic Kitchen': [
    'Grilled Salmon',
    'Wild Mushroom Risotto',
    'Apple Pie',
    'Ribeye Steak',
    'Mashed Potatoes',
    'Pumpkin Soup',
    'Lobster Bisque',
    'Fried Chicken',
    'Cornbread',
    'Gnocchi',
    'Stuffed Bell Peppers',
    'Beef Wellington',
    'Crème Brûlée',
    'Tuna Tartare',
    'Shrimp Scampi',
  ],
  'Spice Garden': [
    'Pad Thai',
    'Chicken Curry',
    'Tom Yum Soup',
    'Green Curry',
    'Mango Sticky Rice',
    'Thai Basil Fried Rice',
    'Red Curry',
    'Massaman Curry',
    'Spring Rolls',
    'Pineapple Fried Rice',
    'Papaya Salad',
    'Thai Iced Tea',
    'Fish Cakes',
    'Beef Satay',
    'Coconut Soup',
  ],
  'Ocean Blue Grill': [
    'Fish and Chips',
    'Clam Chowder',
    'Grilled Shrimp',
    'Lobster Roll',
    'Fish Tacos',
    'Seafood Paella',
    'Grilled Calamari',
    'Crab Cakes',
    'Shrimp Scampi',
    'Tuna Steak',
    'Salmon Burger',
    'Oysters Rockefeller',
    'Mussels Marinara',
    'Scallops',
    'Tuna Tartare',
  ],
  'Golden Harvest': [
    'Cheeseburger',
    'Club Sandwich',
    'French Fries',
    'Chicken Tenders',
    'Chicken Caesar Salad',
    'Buffalo Wings',
    'BLT Sandwich',
    'Grilled Cheese Sandwich',
    'Chicken Fried Steak',
    'Meatloaf',
    'Corned Beef Hash',
    'Reuben Sandwich',
    'Pot Roast',
    'Chicken Pot Pie',
    'Turkey Dinner',
  ],
  'Green Leaf': [
    'Caesar Salad',
    'Caprese Salad',
    'Greek Salad',
    'Spinach Salad',
    'Cobb Salad',
    'Nicoise Salad',
    'Waldorf Salad',
    'Chef Salad',
    'Asian Salad',
    'Quinoa Salad',
    'Fruit Salad',
    'Pasta Salad',
    'Taco Salad',
    'Steak Salad',
    'Beet Salad',
  ],
  'Sunrise Cafe': [
    'Pancakes',
    'French Toast',
    'Waffles',
    'Eggs Benedict',
    'Omelette',
    'Breakfast Burrito',
    'Bagel with Cream Cheese',
    'Avocado Toast',
    'Egg Sandwich',
    'Biscuits and Gravy',
    'Granola with Yogurt',
    'Fruit Smoothie',
    'Breakfast Bowl',
    'English Muffin with Jam',
    'Sausage Links',
  ],
  'LongHorns': [
    'Filet Mignon',
    'New York Strip Steak',
    'Ribeye Steak',
    'T-Bone Steak',
    'Porterhouse Steak',
    'Prime Rib',
    'Sirloin Steak',
    'Flat Iron Steak',
    'Chateaubriand',
    'Skirt Steak',
    'Hanger Steak',
    'Flank Steak',
    'Chuck Eye Steak',
    'Round Steak',
    'Beef Tenderloin',
  ],
  'Mystic Thai': [
    'Pad See Ew',
    'Green Curry',
    'Red Curry',
    'Tom Yum Soup',
    'Pad Thai',
    'Massaman Curry',
    'Thai Basil Chicken',
    'Mango Sticky Rice',
    'Papaya Salad',
    'Coconut Soup',
    'Spring Rolls',
    'Drunken Noodles',
    'Cashew Chicken',
    'Pineapple Fried Rice',
    'Crispy Pork Belly',
  ],
  'Pasta Paradise': [
    'Spaghetti Bolognese',
    'Fettuccine Alfredo',
    'Lasagna',
    'Penne Arrabiata',
    'Ravioli',
    'Carbonara',
    'Pesto Pasta',
    'Mac and Cheese',
    'Linguine with Clams',
    'Shrimp Scampi',
    'Seafood Linguine',
    'Chicken Parmesan',
    'Gnocchi',
    'Tortellini',
    'Stuffed Shells',
  ],
};
